// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /Users/stephanstiefelmaier/Documents/Promotion/repos_cloud/projects/2024/2024-03-06_investigatePtWeights/./source/InvPtW_main.h;
#pragma link C++ defined_in "/Users/stephanstiefelmaier/Documents/Promotion/repos_cloud/projects/2024/2024-03-06_investigatePtWeights/./source/InvPtW_main.cpp";

#endif
